baseURL = 'https://erazemk.com/'
languageCode = 'en'
title = 'Erazem Kokot'

[Params]
    Author = 'Erazem Kokot'
    Description = 'My website / landing page'
    Bio = 'Go developer / Backend engineer'
    Avatar = '/res/avatar.png'
    Email = 'mail@erazemk.com'
    PGP = ''

    [params.social]
        GitHub = 'https://github.com/erazemk'
        LinkedIn = 'https://www.linkedin.com/in/erazemk/'
