baseURL = 'https://erazemk.com/'
languageCode = 'en'
title = 'Erazem Kokot'
enableRobotsTXT = true
disableKinds = ['rss', 'sitemap']

[params]
    author = 'Erazem Kokot'
    description = 'My website / landing page'
    job = 'Go developer / Backend engineer'
    bio = 'Fan of Go, Docker/Podman, Linux and FPGAs, but constantly learning new stuff.'
    avatar = '/res/avatar.png'
    email = 'mail@erazemk.com'
    pgp = '45CADCF24B218D7F155400B0ADE33D31CEE4BEFC'

    [params.social]
        GitHub = 'https://github.com/erazemk'
        LinkedIn = 'https://www.linkedin.com/in/erazemk/'
